# Generated by Django 5.1.2 on 2024-11-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user',
        ),
    ]
