# Generated by Django 5.1.2 on 2024-11-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_rename_name_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='webpage',
            new_name='name',
        ),
    ]
